Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2020-09, with the labels that each got.

#1166 Fix InspectStringMultipleRulesTests to use large enough string to det…
  dlp/api/Snippets.Tests/InspectStringMultipleRulesTests.cs
  dlp/api/Snippets/README.md
Labels: cla: yes, samples

#1157 run/events: Use Unmarshal Types Rather Than dynamic. Fixes #1156
  run/events-pubsub/EventsPubSub.csproj
  run/events-pubsub/Startup.cs
Labels: api: run, cla: yes, samples

#1150 Cloud SQL: Update MySQL/Postgres connectivity samples to demonstrate TCP and Unix Socket connections
  cloud-sql/mysql/README.md
  cloud-sql/mysql/Startup.cs
  cloud-sql/mysql/app.yaml
  cloud-sql/mysql/appsettings.json
  cloud-sql/mysql/runTestsWithMySql.ps1
  cloud-sql/postgres/README.md
  cloud-sql/postgres/Startup.cs
  cloud-sql/postgres/app.yaml
  cloud-sql/postgres/appsettings.json
  cloud-sql/postgres/runTestsWithPostgreSql.ps1
  cloud-sql/sql-server/README.md
  cloud-sql/sql-server/Startup.cs
  cloud-sql/sql-server/app.yaml
  cloud-sql/sql-server/runTestsWithSqlServer.ps1
Labels: cla: yes, samples

#1148 Pub/Sub: Add examples for ordering keys
  pubsub/api/Pubsub.Samples.Tests/CreateSubscriptionWithOrderingTest.cs
  pubsub/api/Pubsub.Samples.Tests/PublishOrderedMessagesTest.cs
  pubsub/api/Pubsub.Samples.Tests/ResumePublishTest.cs
  pubsub/api/Pubsub.Samples/CreateSubscriptionWithOrdering.cs
  pubsub/api/Pubsub.Samples/PublishOrderedMessagesAsync.cs
  pubsub/api/Pubsub.Samples/ResumePublish.cs
Labels: api: pubsub, cla: yes, do not merge, samples

#1138 Spanner: update samples to follow samples guide -1
  spanner/api/Spanner.Samples.Tests/CreateBackupTest.cs
  spanner/api/Spanner.Samples.Tests/CreateDatabaseAsyncTest.cs
  spanner/api/Spanner.Samples.Tests/Spanner.Samples.Tests.csproj
  spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
  spanner/api/Spanner.Samples.Tests/runTests.ps1
  spanner/api/Spanner.Samples/AddColumnAsync.cs
  spanner/api/Spanner.Samples/AddIndexAsync.cs
  spanner/api/Spanner.Samples/AddStoringIndexAsync.cs
  spanner/api/Spanner.Samples/CreateBackup.cs
  spanner/api/Spanner.Samples/CreateDatabaseAsync.cs
  spanner/api/Spanner.Samples/CreateInstance.cs
  spanner/api/Spanner.Samples/DeleteBackup.cs
  spanner/api/Spanner.Samples/InsertDataAsync.cs
  spanner/api/Spanner.Samples/Spanner.Samples.csproj
  spanner/api/Spanner.sln
  spanner/api/SpannerTest/SpannerTest.csproj
  spanner/api/SpannerTest/Tests.cs
Labels: api: spanner, cla: yes, samples

#1164 Specify member type
  iam/api/QuickStartV2/QuickStart.cs
Labels: cla: yes, samples

#1179 [Spanner]: reduce time to delete the old databases and backups to 48 hrs
  spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
Labels: cla: yes, samples

#1181 Add final (really!) Functions sample for Firebase, for analytics
  functions/firebase/Firebase.Tests/Firebase.Tests.csproj
  functions/firebase/Firebase.Tests/FirebaseAnalyticsTest.cs
  functions/firebase/Firebase.sln
  functions/firebase/FirebaseAnalytics/FirebaseAnalytics.csproj
  functions/firebase/FirebaseAnalytics/Function.cs
Labels: cla: yes

#1180 Give the Firestore Reactive sample the correct tag
  functions/firebase/FirestoreReactive/Function.cs
Labels: cla: yes, samples

#1182 chore(functions): replace helloGcs sample with helloGcsGeneric
  functions/helloworld/HelloGcs/Function.cs
  functions/helloworld/HelloGcsGeneric/Function.cs
  functions/helloworld/HelloGcsGeneric/HelloGcsGeneric.csproj
  functions/helloworld/HelloWorld.Tests/HelloGcsGenericTest.cs
  functions/helloworld/HelloWorld.Tests/HelloGcsTest.cs
  functions/helloworld/HelloWorld.Tests/HelloGcsUnitTest.cs
  functions/helloworld/HelloWorld.Tests/HelloWorld.Tests.csproj
  functions/helloworld/HelloWorld.sln
Labels: api: cloudfunctions, cla: yes, samples

#1186 Pub/Sub: update region tags
  pubsub/api/Pubsub.Samples/CreateSubscriptionWithOrdering.cs
  pubsub/api/Pubsub.Samples/PublishOrderedMessagesAsync.cs
  pubsub/api/Pubsub.Samples/ResumePublish.cs
Labels: cla: yes

#1184 Add Firestore Collection Group Query sample
  firestore/api/QueryData/Program.cs
Labels: cla: yes

#1185 Added comments to improve clarity of samples
  cloud-sql/mysql/Startup.cs
  cloud-sql/postgres/Startup.cs
  cloud-sql/sql-server/Startup.cs
Labels: cla: yes, samples

#1187 [Pub/Sub]: Detach Subscription Sample
  pubsub/api/Pubsub.Samples.Tests/DetachSubscriptionTest.cs
  pubsub/api/Pubsub.Samples/DetachSubscription.cs
  pubsub/api/Pubsub.Samples/Pubsub.Samples.csproj
Labels: cla: yes, samples

#1188 Spanner: add NUMERIC samples
  spanner/api/Spanner.Samples.Tests/AddNumericColumnTest.cs
  spanner/api/Spanner.Samples.Tests/QueryDataWithNumericParameterTest.cs
  spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
  spanner/api/Spanner.Samples.Tests/UpdateDataWithNumericTest.cs
  spanner/api/Spanner.Samples/AddNumericColumnAsync.cs
  spanner/api/Spanner.Samples/QueryDataWithNumericParameterAsync.cs
  spanner/api/Spanner.Samples/Spanner.Samples.csproj
  spanner/api/Spanner.Samples/UpdateDataWithNumericAsync.cs
Labels: api: spanner, cla: yes, samples

#1191 [Spanner]: Delete five oldest databases if instance reaches the database limit
  spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
Labels: cla: yes, samples

#1196 Moved run/events-* to eventarc/ and other minor changes to match the …
  eventarc/audit-storage/AuditStorage.csproj
  eventarc/audit-storage/Dockerfile
  eventarc/audit-storage/Program.cs
  eventarc/audit-storage/README.md
  eventarc/audit-storage/Startup.cs
  eventarc/audit-storage/anthos.md
  eventarc/pubsub/Dockerfile
  eventarc/pubsub/Program.cs
  eventarc/pubsub/PubSub.csproj
  eventarc/pubsub/README.md
  eventarc/pubsub/Startup.cs
  eventarc/pubsub/anthos.md
  run/.gcloudignore
  run/README.md
  run/events-pubsub/README.md
  run/events-pubsub/anthos.md
Labels: cla: yes, samples

#1192 [IAM] Remove old quickstart
  iam/api/QuickStart/QuickStart.cs
  iam/api/QuickStart/QuickStart.csproj
  iam/api/QuickStart/README.md
  iam/api/QuickStartTest/QuickStartTest.cs
  iam/api/QuickStartTest/QuickStartTest.csproj
  iam/api/QuickStartTest/runTests.ps1
  iam/api/QuickStartV2/QuickStart.cs
  iam/api/QuickStartV2/QuickStart.csproj
  iam/api/QuickStartV2/README.md
  iam/api/QuickStartV2Test/QuickStartTest.cs
  iam/api/QuickStartV2Test/QuickStartTest.csproj
  iam/api/QuickStartV2Test/runTests.ps1
Labels: cla: yes, samples

#1198 Add tags to Functions "hello world" project files
  functions/helloworld/HelloWorld/HelloWorld.csproj
  functions/helloworld/HelloWorldFSharp/HelloWorldFSharp.fsproj
  functions/helloworld/HelloWorldVb/HelloWorldVb.vbproj
Labels: cla: yes, samples
