Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2020-05, with the labels that each got.

#991 spanner: Backup and Restore samples
  spanner/api/QuickStart/QuickStart.csproj
  spanner/api/Spanner/CancelBackupOperation.cs
  spanner/api/Spanner/CreateBackup.cs
  spanner/api/Spanner/DeleteBackup.cs
  spanner/api/Spanner/GetBackupOperations.cs
  spanner/api/Spanner/GetBackups.cs
  spanner/api/Spanner/GetDatabaseOperations.cs
  spanner/api/Spanner/Program.cs
  spanner/api/Spanner/RestoreDatabase.cs
  spanner/api/Spanner/Spanner.csproj
  spanner/api/Spanner/UpdateBackup.cs
  spanner/api/SpannerTest/Tests.cs
  spanner/api/SpannerTest/runTests.ps1
Labels: api: spanner, cla: yes

#1036 [IAP]: Updates IAP samples.
  identity-aware-proxy/IAPClient/IAPClient.cs
  identity-aware-proxy/IAPClient/IAPClient.csproj
  identity-aware-proxy/IAPClient/Main.cs
  identity-aware-proxy/IAPClientTest/IAPClientTest.cs
  identity-aware-proxy/IAPClientTest/IAPClientTest.csproj
Labels: api: iap, cla: yes

#1049 docs: removes unused dialogflow code samples
  dialogflow/api/DialogflowSamples/ContextManagement.cs
  dialogflow/api/DialogflowSamples/DialogflowSamples.cs
  dialogflow/api/DialogflowSamples/EntityManagement.cs
  dialogflow/api/DialogflowSamples/EntityTypeManagement.cs
  dialogflow/api/DialogflowSamples/README.md
  dialogflow/api/DialogflowSamples/SessionEntityTypeManagement.cs
  dialogflow/api/Test/ContextManagementTests.cs
  dialogflow/api/Test/EntityManagementTests.cs
  dialogflow/api/Test/EntityTypeManagementTests.cs
  dialogflow/api/Test/SessionEntityTypeManagementTests.cs
Labels: cla: yes

#1045 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#980 Add SecurityCenter code samples
  pubsub/api/PubsubSample/Program.cs
  securitycenter/api/src/CreateNotificationConfigSnippets.g.cs
  securitycenter/api/src/DeleteNotificationConfigSnippets.g.cs
  securitycenter/api/src/GetNotificationConfigSnippets.g.cs
  securitycenter/api/src/ListNotificationConfigSnippets.g.cs
  securitycenter/api/src/Snippets.csproj
  securitycenter/api/src/UpdateNotificationConfigSnippets.g.cs
  securitycenter/api/tests/ConfigFixture.cs
  securitycenter/api/tests/SecurityCenterTests.cs
  securitycenter/api/tests/Tests.csproj
  securitycenter/api/tests/runTest.ps1
Labels: cla: yes

#1053 Added Cloud Run Events C# samples
  run/events/Dockerfile
  run/events/HelloEvents.csproj
  run/events/Program.cs
  run/events/README.md
  run/events/Startup.cs
Labels: cla: yes
