Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2020-10, with the labels that each got.

#1202 fix(run): restore missing gcloudignore
  run/helloworld/.gcloudignore
Labels: api: run, cla: yes, samples

#1203 Spanner: sample with custom timeout and retry settings
  spanner/api/Spanner.Samples.Tests/CustomTimeoutsAndRetriesTest.cs
  spanner/api/Spanner.Samples/CustomTimeoutsAndRetriesAsync.cs
Labels: api: spanner, cla: yes, samples

#1205 Update Functions dependencies
  functions/concepts/Concepts.Tests/Concepts.Tests.csproj
  functions/concepts/EnvironmentVariables/EnvironmentVariables.csproj
  functions/concepts/ExecutionCount/ExecutionCount.csproj
  functions/concepts/FileSystem/FileSystem.csproj
  functions/concepts/LazyFields/LazyFields.csproj
  functions/concepts/Retry/Retry.csproj
  functions/concepts/Scopes/Scopes.csproj
  functions/concepts/TimeBoundedRetries/TimeBoundedRetries.csproj
  functions/firebase/Firebase.Tests/Firebase.Tests.csproj
  functions/firebase/FirebaseAnalytics/FirebaseAnalytics.csproj
  functions/firebase/FirebaseAuth/FirebaseAuth.csproj
  functions/firebase/FirebaseFirestore/FirebaseFirestore.csproj
  functions/firebase/FirebaseRemoteConfig/FirebaseRemoteConfig.csproj
  functions/firebase/FirebaseRtdb/FirebaseRtdb.csproj
  functions/firebase/FirestoreReactive/FirestoreReactive.csproj
  functions/helloworld/HelloGcs/HelloGcs.csproj
  functions/helloworld/HelloHttp/HelloHttp.csproj
  functions/helloworld/HelloPubSub/HelloPubSub.csproj
  functions/helloworld/HelloPubSubFSharp/HelloPubSubFSharp.fsproj
  functions/helloworld/HelloPubSubVb/HelloPubSubVb.vbproj
  functions/helloworld/HelloWorld.Tests/HelloWorld.Tests.csproj
  functions/helloworld/HelloWorld/HelloWorld.csproj
  functions/helloworld/HelloWorldFSharp/HelloWorldFSharp.fsproj
  functions/helloworld/HelloWorldVb/HelloWorldVb.vbproj
  functions/http/Cors/Cors.csproj
  functions/http/Http.Tests/Http.Tests.csproj
  functions/http/HttpFormData/HttpFormData.csproj
  functions/http/HttpRequestMethod/HttpRequestMethod.csproj
  functions/http/ParseContentType/ParseContentType.csproj
  functions/http/SendHttpRequest/SendHttpRequest.csproj
  functions/imagemagick/ImageMagick/ImageMagick.csproj
  functions/logging/LogHelloWorld/LogHelloWorld.csproj
  functions/logging/Logging.Tests/Logging.Tests.csproj
  functions/slack/SlackKnowledgeGraphSearch/SlackKnowledgeGraphSearch.csproj
Labels: cla: yes

#1207 Don't parse request body when there isn't one
  functions/helloworld/HelloHttp/Function.cs
  functions/helloworld/HelloWorld.Tests/HelloHttpTest.cs
Labels: cla: yes

#1212 Add new updated SQL Server sample region tags.
  cloud-sql/sql-server/Startup.cs
Labels: cla: yes, samples

#1213 Another updated SQL Server sample region tag.
  cloud-sql/sql-server/Controllers/HomeController.cs
Labels: cla: yes

#1214 Remove outdated SQL Server sample region tags.
  cloud-sql/sql-server/Controllers/HomeController.cs
  cloud-sql/sql-server/Startup.cs
Labels: cla: yes
