Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2020-06, with the labels that each got.

#1055 Updates CODEOWNERS.
  CODEOWNERS
Labels: cla: yes

#1054 Update README to show "Upload Files"
  speech/api/README.md
  speech/api/cloud-shell-editor-upload-files.png
  speech/api/cloud-shell-import-file.png
Labels: cla: yes

#1058 Address linter concerns with Cloud Run samples
  run/events/Program.cs
  run/events/Startup.cs
Labels: cla: yes

#1047 fix(spanner): UpdateBackup test Expire time issue
  spanner/api/Spanner/UpdateBackup.cs
  spanner/api/SpannerTest/Tests.cs
Labels: cla: yes

#1029 Bigtable: test timeout issue
  bigtable/api/BigtableTest/BigtableTest.csproj
  bigtable/api/BigtableTest/Tests.cs
  bigtable/api/BigtableTest/runTests.ps1
  bigtable/api/HelloWorld/HelloWorld.cs
  bigtable/api/InstanceAdminExample/InstanceAdmin.cs
  bigtable/api/QuickStart/QuickStart.cs
  bigtable/api/TableAdminExample/TableAdmin.cs
Labels: cla: yes

#1070 fix: update f# sample to .net core 3.1
  BuildTools.psm1
  appengine/flexible/F#/F#.fsproj
  appengine/flexible/F#/Program.fs
  appengine/flexible/F#/Startup.fs
  appengine/flexible/F#/appsettings.Development.json
  appengine/flexible/F#/appsettings.json
  appengine/flexible/F#/runTests.ps1
Labels: cla: yes

#1075 fix: renables and fixes DetectIntentTextsTest
  dialogflow/api/Test/DetectIntentTextsTest.cs
  dialogflow/api/Test/runTests.ps1
Labels: cla: yes

#1082 Fixes broken create trigger test
  dlp/api/DlpTest/DlpTest.cs
Labels: cla: yes

#1074 feat: adds create BigQuery job sample
  bigquery/api/Snippets/CreateJob.cs
  bigquery/api/Snippets/Test.cs
Labels: cla: yes

#1083 Add risk analysis and trigger snippets and tests
  dlp/api/Snippets.Tests/TriggersCreateTests.cs
  dlp/api/Snippets.Tests/TriggersDeleteTests.cs
  dlp/api/Snippets.Tests/TriggersListTests.cs
  dlp/api/Snippets/InspectBigQuery.cs
  dlp/api/Snippets/InspectCloudDataStore.cs
  dlp/api/Snippets/InspectGoogleCloudStorage.cs
  dlp/api/Snippets/RiskAnalysisCreateCategoricalStats.cs
  dlp/api/Snippets/RiskAnalysisCreateKAnonymity.cs
  dlp/api/Snippets/RiskAnalysisCreateKMap.cs
  dlp/api/Snippets/RiskAnalysisCreateLDiversity.cs
  dlp/api/Snippets/RiskAnalysisCreateNumericalStats.cs
  dlp/api/Snippets/TriggersCreate.cs
  dlp/api/Snippets/TriggersDelete.cs
  dlp/api/Snippets/TriggersList.cs
Labels: cla: yes

#1084 Add DeidentifyWithSimpleWordList and test
  dlp/api/Snippets.Tests/DeidentifyWithSimpleWordListTests.cs
  dlp/api/Snippets/DeidentifyWithSimpleWordList.cs
Labels: cla: yes

#1085 Add exclusion rule example
  dlp/api/Snippets.Tests/DeidentifyWithExceptionListTest.cs
  dlp/api/Snippets/DeidentifyWithExceptionList.cs
Labels: cla: yes

#1088 Fix copy paste bug
  dlp/api/Snippets.Tests/DeidentifyWithExceptionListTest.cs
  dlp/api/Snippets.Tests/JobsCreateTests.cs
  dlp/api/Snippets.Tests/JobsDeleteTests.cs
  dlp/api/Snippets.Tests/JobsListTests.cs
  dlp/api/Snippets.Tests/TriggersCreateTests.cs
  dlp/api/Snippets/DeidentifyWithExceptionList.cs
  dlp/api/Snippets/JobsList.cs
Labels: cla: yes

#1087 [bigtable] Update region tags for reads and filters
  bigtable/api/Snippets/Filters.cs
  bigtable/api/Snippets/Reads.cs
Labels: cla: yes

#1089 Add custom hotword snippet and test
  dlp/api/Snippets.Tests/InspectStringCustomHotwordTests.cs
  dlp/api/Snippets.Tests/JobsDeleteTests.cs
  dlp/api/Snippets/InspectStringCustomHotword.cs
Labels: cla: yes

#1072 fix: add a code sample for CreateInstance
  spanner/api/Spanner/CreateInstance.cs
  spanner/api/SpannerTest/Tests.cs
Labels: api: spanner, cla: yes

#1090 Add multiple rules snippet and tests
  dlp/api/Snippets.Tests/InspectStringMultipleRulesTests.cs
  dlp/api/Snippets/InspectStringMultipleRules.cs
Labels: cla: yes

#1091 Add snippet and tests for inspect string without overlap
  dlp/api/Snippets.Tests/InspectStringWithoutOverlapTests.cs
  dlp/api/Snippets/InspectStringWithoutOverlap.cs
Labels: cla: yes

#1092 fix: skip TestUpdateBackup test
  spanner/api/SpannerTest/Tests.cs
Labels: api: spanner, cla: yes

#1086 fix-it(Cloud Monitoring Api): Change the quick start documentation.
  monitoring/api/QuickStart/QuickStart.cs
Labels: cla: yes

#1063 fix: update DELETE samples to match docs
  spanner/api/Spanner/Program.cs
  spanner/api/SpannerTest/Tests.cs
Labels: api: spanner, cla: yes

#1093 Remove old dlp snippets and tests
  dlp/api/.editorconfig
  dlp/api/DlpSample/DeIdentify.cs
  dlp/api/DlpSample/DlpSample.csproj
  dlp/api/DlpSample/DlpSamplesUtils.cs
  dlp/api/DlpSample/InspectSamples.cs
  dlp/api/DlpSample/InspectTemplates.cs
  dlp/api/DlpSample/Jobs.cs
  dlp/api/DlpSample/Metadata.cs
  dlp/api/DlpSample/Program.cs
  dlp/api/DlpSample/RedactSamples.cs
  dlp/api/DlpSample/RiskAnalysis.cs
  dlp/api/DlpSample/Triggers.cs
  dlp/api/DlpTest/DlpTest.cs
  dlp/api/DlpTest/DlpTest.csproj
  dlp/api/DlpTest/InspectTests.cs
  dlp/api/DlpTest/RedactTests.cs
  dlp/api/DlpTest/TemplateTests.cs
  dlp/api/DlpTest/kmsPlain.txt
  dlp/api/DlpTest/resources/dates-correct.csv
  dlp/api/DlpTest/resources/dates-input.csv
  dlp/api/DlpTest/resources/harmless.txt
  dlp/api/DlpTest/resources/test.png
  dlp/api/DlpTest/resources/test.txt
  dlp/api/DlpTest/runTest.ps1
  dlp/api/DlpTest/test.txt
  dlp/api/Snippets.Tests/runTest.ps1
Labels: cla: yes

#1096 Adds pheonixblade9 as CODEOWNER for DLP
  CODEOWNERS
Labels: cla: yes

#1095 Add InspectStringWithExclusionRegex and tests
  dlp/api/Snippets.Tests/InspectStringWithExclusionRegexTests.cs
  dlp/api/Snippets/InspectStringWithExclusionRegex.cs
Labels: cla: yes

#1097 Add InspectStringCustomExcludingSubstring and tests
  dlp/api/Snippets.Tests/InspectStringCustomExcludingSubstringTests.cs
  dlp/api/Snippets/InspectStringCustomExcludingSubstring.cs
Labels: cla: yes

#1099 Add InspectStringCustomOmitOverlap and tests
  dlp/api/Snippets.Tests/InspectStringCustomOmitOverlapTests.cs
  dlp/api/Snippets/InspectStringCustomOmitOverlap.cs
Labels: cla: yes

#1100 Add InspectStringOmitOverlap snippet and tests
  dlp/api/Snippets.Tests/InspectStringOmitOverlapTests.cs
  dlp/api/Snippets/InspectStringOmitOverlap.cs
Labels: cla: yes

#1079 IAP sample rewrite.
  identity-aware-proxy/IAP.sln
  identity-aware-proxy/IAPClient/IAPClient.cs
  identity-aware-proxy/IAPClient/IAPClient.csproj
  identity-aware-proxy/IAPClient/IAPTokenVerification.cs
  identity-aware-proxy/IAPClient/Main.cs
  identity-aware-proxy/IAPClient/README.md
  identity-aware-proxy/IAPClientTest/IAPClientTest.cs
  identity-aware-proxy/IAPClientTest/IAPClientTest.csproj
  identity-aware-proxy/IAPClientTest/IAPClientTests.cs
  identity-aware-proxy/IAPClientTest/IAPFixture.cs
  identity-aware-proxy/IAPClientTest/IAPTokenVerificationTests.cs
  identity-aware-proxy/IAPClientTest/runTest.ps1
Labels: api: iap, cla: yes

#1102 Convert snippets to use global region endpoint
  dlp/api/Snippets.Tests/DlpTestFixture.cs
  dlp/api/Snippets.Tests/InspectTemplateCreateTests.cs
  dlp/api/Snippets.Tests/InspectTemplateListTests.cs
  dlp/api/Snippets.Tests/TriggersListTests.cs
  dlp/api/Snippets/DeidentifyWithDateShift.cs
  dlp/api/Snippets/DeidentifyWithExceptionList.cs
  dlp/api/Snippets/DeidentifyWithFpe.cs
  dlp/api/Snippets/DeidentifyWithMasking.cs
  dlp/api/Snippets/DeidentifyWithSimpleWordList.cs
  dlp/api/Snippets/InspectBigQuery.cs
  dlp/api/Snippets/InspectCloudDataStore.cs
  dlp/api/Snippets/InspectFile.cs
  dlp/api/Snippets/InspectGoogleCloudStorage.cs
  dlp/api/Snippets/InspectString.cs
  dlp/api/Snippets/InspectStringCustomExcludingSubstring.cs
  dlp/api/Snippets/InspectStringCustomHotword.cs
  dlp/api/Snippets/InspectStringCustomOmitOverlap.cs
  dlp/api/Snippets/InspectStringMultipleRules.cs
  dlp/api/Snippets/InspectStringOmitOverlap.cs
  dlp/api/Snippets/InspectStringWithExclusionDict.cs
  dlp/api/Snippets/InspectStringWithExclusionDictSubstring.cs
  dlp/api/Snippets/InspectStringWithExclusionRegex.cs
  dlp/api/Snippets/InspectStringWithoutOverlap.cs
  dlp/api/Snippets/InspectTemplateCreate.cs
  dlp/api/Snippets/InspectTemplateList.cs
  dlp/api/Snippets/JobsCreate.cs
  dlp/api/Snippets/JobsList.cs
  dlp/api/Snippets/RedactImage.cs
  dlp/api/Snippets/TriggersCreate.cs
  dlp/api/Snippets/TriggersList.cs
Labels: cla: yes

#1109 [bigtable] - region tag update for reads/filters
  bigtable/api/Snippets/Filters.cs
  bigtable/api/Snippets/Reads.cs
Labels: cla: yes

#1050 pub/sub: update samples to follow samples guide
  pubsub/api/Pubsub.Samples.Tests/AcknowledgeMessageTest.cs
  pubsub/api/Pubsub.Samples.Tests/AcknowledgeMessageWithFlowControlTest.cs
  pubsub/api/Pubsub.Samples.Tests/CreateSubscriptionTest.cs
  pubsub/api/Pubsub.Samples.Tests/CreateTopicTest.cs
  pubsub/api/Pubsub.Samples.Tests/DeleteSubscriptionTest.cs
  pubsub/api/Pubsub.Samples.Tests/DeleteTopicTest.cs
  pubsub/api/Pubsub.Samples.Tests/GetSubscriptionPolicyTest.cs
  pubsub/api/Pubsub.Samples.Tests/GetTopicIamPolicyTest.cs
  pubsub/api/Pubsub.Samples.Tests/ListSubscriptionsTest.cs
  pubsub/api/Pubsub.Samples.Tests/ListTopicsTest.cs
  pubsub/api/Pubsub.Samples.Tests/PublishBatchMessageTest.cs
  pubsub/api/Pubsub.Samples.Tests/PublishMessageTest.cs
  pubsub/api/Pubsub.Samples.Tests/Pubsub.Samples.Tests.csproj
  pubsub/api/Pubsub.Samples.Tests/PubsubFixture.cs
  pubsub/api/Pubsub.Samples.Tests/PullMessagesSyncTest.cs
  pubsub/api/Pubsub.Samples.Tests/SetSubscriptionIamPolicyTest.cs
  pubsub/api/Pubsub.Samples.Tests/SetTopicIamPolicyTest.cs
  pubsub/api/Pubsub.Samples.Tests/SubscriptionPolicyPermisssionsTest.cs
  pubsub/api/Pubsub.Samples.Tests/TopicIamPolicyPermissionsTest.cs
  pubsub/api/Pubsub.Samples.Tests/runTest.ps1
  pubsub/api/Pubsub.Samples/CreateSubscription.cs
  pubsub/api/Pubsub.Samples/CreateTopic.cs
  pubsub/api/Pubsub.Samples/DeleteSubscription.cs
  pubsub/api/Pubsub.Samples/DeleteTopic.cs
  pubsub/api/Pubsub.Samples/GetSubscriptionIamPolicy.cs
  pubsub/api/Pubsub.Samples/GetTopicIamPolicy.cs
  pubsub/api/Pubsub.Samples/ListProjectTopics.cs
  pubsub/api/Pubsub.Samples/ListSubscriptions.cs
  pubsub/api/Pubsub.Samples/PublishBatchedMessagesAsync.cs
  pubsub/api/Pubsub.Samples/PublishMessagesAsync.cs
  pubsub/api/Pubsub.Samples/Pubsub.Samples.csproj
  pubsub/api/Pubsub.Samples/PullMessagesAsync.cs
  pubsub/api/Pubsub.Samples/PullMessagesSync.cs
  pubsub/api/Pubsub.Samples/PullMessagesWithFlowControlAsync.cs
  pubsub/api/Pubsub.Samples/SetSubscriptionIamPolicy.cs
  pubsub/api/Pubsub.Samples/SetTopicIamPolicy.cs
  pubsub/api/Pubsub.Samples/TestSubscriptionIamPermissions.cs
  pubsub/api/Pubsub.Samples/TestTopicIamPermissions.cs
  pubsub/api/Pubsub.sln
  pubsub/api/PubsubSample/Program.cs
  pubsub/api/PubsubSample/Pubsub.csproj
  pubsub/api/PubsubTest/PubsubTest.cs
  pubsub/api/PubsubTest/PubsubTest.csproj
  pubsub/api/QuickStart/QuickStart.cs
  pubsub/api/QuickStart/QuickStart.csproj
  pubsub/api/README.md
Labels: cla: yes

#1108 Add Events for Cloud Run samples for .NET
  run/README.md
  run/events-gcs/Dockerfile
  run/events-gcs/EventsGcs.csproj
  run/events-gcs/Program.cs
  run/events-gcs/README.md
  run/events-gcs/Startup.cs
  run/events-pubsub/Dockerfile
  run/events-pubsub/EventsPubSub.csproj
  run/events-pubsub/Program.cs
  run/events-pubsub/README.md
  run/events-pubsub/Startup.cs
  run/events/Dockerfile
  run/events/README.md
  run/events/Startup.cs
Labels: cla: yes

#968 [IAM] Update quickstart samples
  iam/api/QuickStart/QuickStart.cs
  iam/api/QuickStartTest/QuickStartTest.csproj
  iam/api/QuickStartV2/QuickStart.cs
  iam/api/QuickStartV2/QuickStart.csproj
  iam/api/QuickStartV2/README.md
  iam/api/QuickStartV2Test/QuickStartTest.cs
  iam/api/QuickStartV2Test/QuickStartTest.csproj
  iam/api/QuickStartV2Test/runTests.ps1
Labels: cla: yes

#1116 Update Run Events Tags
  run/events-gcs/Program.cs
  run/events-pubsub/Program.cs
Labels: cla: yes
