Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2020-12, with the labels that each got.

#1226 feat: [Speech] Adds a profanity filter sample
  speech/api/Recognize/Recognize.cs
  speech/api/SpeechTest/SpeechTest.cs
Labels: cla: yes, samples

#1223 feat(samples): add samples for analyzeIamPolicy and analyzeIamPolicyLongrunning
  asset/api/Asset.Samples.Tests/AnalyzeIamPolicyLongrunningBigqueryTest.cs
  asset/api/Asset.Samples.Tests/AnalyzeIamPolicyLongrunningGcsTest.cs
  asset/api/Asset.Samples.Tests/AnalyzeIamPolicyTest.cs
  asset/api/Asset.Samples.Tests/AssetFixture.cs
  asset/api/Asset.Samples/AnalyzeIamPolicy.cs
  asset/api/Asset.Samples/AnalyzeIamPolicyLongrunningBigquery.cs
  asset/api/Asset.Samples/AnalyzeIamPolicyLongrunningGcs.cs
  asset/api/Asset.Samples/Asset.Samples.csproj
Labels: api: cloudasset, cla: yes, samples

#1228 refactor: quickstart now uses gcs
  speech/api/QuickStart/QuickStart.cs
Labels: cla: yes, samples

#1229 docs: Wrap samples with future prefix
  securitycenter/api/src/CreateNotificationConfigSnippets.g.cs
  securitycenter/api/src/DeleteNotificationConfigSnippets.g.cs
  securitycenter/api/src/GetNotificationConfigSnippets.g.cs
  securitycenter/api/src/ListNotificationConfigSnippets.g.cs
  securitycenter/api/src/UpdateNotificationConfigSnippets.g.cs
Labels: cla: yes, samples

#1233 docs: homogenize region tags
  spanner/api/Spanner/GetBackupOperations.cs
  spanner/api/Spanner/GetBackups.cs
  spanner/api/Spanner/RestoreDatabase.cs
Labels: cla: yes, kokoro:force-run, samples

#1236 docs: update some region tags missed in PR 1233
  iam/api/Access/AddMember.cs
  spanner/api/Spanner/GetDatabaseOperations.cs
Labels: cla: yes, samples
