Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2021-04, with the labels that each got.

#1287 chore: removed dialogflow unsupported samples
  dialogflow/api/Dialogflow.sln
  dialogflow/api/DialogflowSamples/DetectIntentStream.cs
  dialogflow/api/DialogflowSamples/DetectIntentTexts.cs
  dialogflow/api/DialogflowSamples/DialogflowSamples.cs
  dialogflow/api/DialogflowSamples/DialogflowSamples.csproj
  dialogflow/api/DialogflowSamples/IntentManagement.cs
  dialogflow/api/DialogflowSamples/README.md
  dialogflow/api/DialogflowSamples/Remove-Resources.ps1
  dialogflow/api/README.md
  dialogflow/api/Test/DetectIntentStreamTest.cs
  dialogflow/api/Test/DetectIntentTextsTest.cs
  dialogflow/api/Test/DialogflowSampleTests.csproj
  dialogflow/api/Test/DialogflowTest.cs
  dialogflow/api/Test/IntentManagementTests.cs
  dialogflow/api/Test/runTests.ps1
  dialogflow/api/resources/book_a_room.wav
Labels: cla: yes, samples

#1288 chore: removed Translate unsupported samples
  translate/api/QuickStart/Program.cs
  translate/api/QuickStart/QuickStart.csproj
  translate/api/QuickStart/README.md
  translate/api/QuickStart/runTests.ps1
  translate/api/Snippets/DetectLanguage.cs
  translate/api/Snippets/ListLanguageCodes.cs
  translate/api/Snippets/ListLanguageNames.cs
  translate/api/Snippets/README.md
  translate/api/Snippets/Snippets.csproj
  translate/api/Snippets/Test.cs
  translate/api/Snippets/TranslateText.cs
  translate/api/Snippets/TranslateTextWithModel.cs
  translate/api/Snippets/runTests.ps1
  translate/api/Tests/BatchTranslateTests.cs
  translate/api/Tests/BatchTranslateWithGlossaryAndModelTests.cs
  translate/api/Tests/BatchTranslateWithGlossaryTests.cs
  translate/api/Tests/BatchTranslateWithModelTests.cs
  translate/api/Tests/DetectLanguageTests.cs
  translate/api/Tests/GetGlossaryTests.cs
  translate/api/Tests/GetSupportedLanguagesTests.cs
  translate/api/Tests/GetSupportedLanguagesWithTargetTests.cs
  translate/api/Tests/ListGlossaryTests.cs
  translate/api/Tests/Tests.csproj
  translate/api/Tests/TranslateFixture.cs
  translate/api/Tests/TranslateTextTests.cs
  translate/api/Tests/TranslateTextWithGlossaryAndModelTests.cs
  translate/api/Tests/TranslateTextWithGlossaryTests.cs
  translate/api/Tests/TranslateTextWithModelTests.cs
  translate/api/Tests/runTests.ps1
  translate/api/Translate.sln
  translate/api/TranslateV3Samples/BatchTranslateText.cs
  translate/api/TranslateV3Samples/BatchTranslateTextWithGlossary.cs
  translate/api/TranslateV3Samples/BatchTranslateTextWithGlossaryAndModel.cs
  translate/api/TranslateV3Samples/BatchTranslateTextWithModel.cs
  translate/api/TranslateV3Samples/CreateGlossary.cs
  translate/api/TranslateV3Samples/DeleteGlossary.cs
  translate/api/TranslateV3Samples/DetectLanguage.cs
  translate/api/TranslateV3Samples/GetGlossary.cs
  translate/api/TranslateV3Samples/GetSupportedLanguages.cs
  translate/api/TranslateV3Samples/GetSupportedLanguagesForTarget.cs
  translate/api/TranslateV3Samples/ListGlossary.cs
  translate/api/TranslateV3Samples/Program.cs
  translate/api/TranslateV3Samples/TranslateText.cs
  translate/api/TranslateV3Samples/TranslateTextWithGlossary.cs
  translate/api/TranslateV3Samples/TranslateTextWithGlossaryAndModel.cs
  translate/api/TranslateV3Samples/TranslateTextWithModel.cs
  translate/api/TranslateV3Samples/TranslateV3Samples.csproj
Labels: cla: yes, samples

#1296 chore: Remove Language unsupported samples
  language/api/Analyze.sln
  language/api/Analyze/Analyze.csproj
  language/api/Analyze/Program.cs
  language/api/AnalyzeTest/AnalyzeTest.cs
  language/api/AnalyzeTest/AnalyzeTest.csproj
  language/api/AnalyzeTest/runTests.ps1
  language/api/QuickStart/QuickStart.cs
  language/api/QuickStart/QuickStart.csproj
  language/api/README.md
Labels: cla: yes, samples

#1284 feat: add Spanner samples for customer managed encryption keys
  spanner/api/QuickStart/QuickStart.csproj
  spanner/api/Spanner.Samples.Tests/CreateBackupWithEncryptionKeyAsyncTest.cs
  spanner/api/Spanner.Samples.Tests/CreateDatabaseWithEncryptionKeyAsyncTest.cs
  spanner/api/Spanner.Samples.Tests/RestoreDatabaseWithEncryptionKeyAsyncTest.cs
  spanner/api/Spanner.Samples.Tests/Spanner.Samples.Tests.csproj
  spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
  spanner/api/Spanner.Samples/CreateBackupWithEncryptionAsync.cs
  spanner/api/Spanner.Samples/CreateDatabaseWithEncryptionAsync.cs
  spanner/api/Spanner.Samples/RestoreDatabaseWithEncryptionAsync.cs
  spanner/api/Spanner.Samples/Spanner.Samples.csproj
  spanner/api/Spanner/Spanner.csproj
Labels: api: spanner, cla: yes, samples

#1303 Debranding logging samples from Stackdriver
  logging/api/README.md
Labels: cla: yes, priority: p2, samples, type: process

#1306 feat: add blunderbuss config to cloud iot label
  .github/blunderbuss.yml
Labels: cla: yes, samples

#1283 chore: removing vision unsupported samples
  vision/api/Detect/Detect.csproj
  vision/api/Detect/Program.cs
  vision/api/DetectFaces/DetectFaces.cs
  vision/api/DetectFaces/DetectFaces.csproj
  vision/api/QuickStart/QuickStart.cs
  vision/api/QuickStart/QuickStart.csproj
  vision/api/QuickStart/wakeupcat.jpg
  vision/api/README.md
  vision/api/Vision.sln
  vision/api/VisionTest/VisionTest.cs
  vision/api/VisionTest/VisionTest.csproj
  vision/api/VisionTest/data/HodgeConj.pdf
  vision/api/VisionTest/data/bonito.gif
  vision/api/VisionTest/data/cat.jpg
  vision/api/VisionTest/data/city.jpg
  vision/api/VisionTest/data/face.png
  vision/api/VisionTest/data/faulkner.jpg
  vision/api/VisionTest/data/logo.jpg
  vision/api/VisionTest/data/mountain.jpg
  vision/api/VisionTest/data/no-text.jpg
  vision/api/VisionTest/data/puppies.jpg
  vision/api/VisionTest/data/sabertooth.gif
  vision/api/VisionTest/data/shoes_1.jpg
  vision/api/VisionTest/data/succulents.jpg
  vision/api/VisionTest/data/sunbeamkitties.jpg
  vision/api/VisionTest/data/text.jpg
  vision/api/VisionTest/data/tower.jpg
  vision/api/VisionTest/data/wakeupcat.jpg
  vision/api/VisionTest/runTests.ps1
Labels: cla: yes, samples
