Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2021-08, with the labels that each got.

#1386 Intialize DB before app run in Cloud SQL samples
  cloud-sql/mysql/Program.cs
  cloud-sql/postgres/Program.cs
  cloud-sql/sql-server/Program.cs
Labels: cla: yes, samples

#1437 build: Ignore dependecy updates for apps that need modernization.
  .github/renovate.json
Labels: cla: yes, samples

#1454 fix(Asset): Modify samples to acommodate API breaking change.
  asset/api/Asset.Samples.Tests/AnalyzeIamPolicyLongrunningBigqueryTest.cs
  asset/api/Asset.Samples.Tests/AnalyzeIamPolicyLongrunningGcsTest.cs
  asset/api/Asset.Samples.Tests/Asset.Samples.Tests.csproj
  asset/api/Asset.Samples/AnalyzeIamPolicyLongrunningBigquery.cs
  asset/api/Asset.Samples/AnalyzeIamPolicyLongrunningGcs.cs
  asset/api/Asset.Samples/Asset.Samples.csproj
  asset/api/Asset.sln
Labels: cla: yes, api: cloudasset, samples

#1399 feat: add samples for tagging
  spanner/api/Spanner.Samples.Tests/RequestTagAsyncTest.cs
  spanner/api/Spanner.Samples.Tests/TransactionTagAsyncTest.cs
  spanner/api/Spanner.Samples/RequestTagAsync.cs
  spanner/api/Spanner.Samples/TransactionTagAsync.cs
Labels: cla: yes, samples

#1455 chore(storage): Undo dependecy update
  storage/api/Storage/Storage.csproj
Labels: cla: yes, api: storage, samples

#1201 [Storage]: remove old samples
  storage/api/Storage.sln
  storage/api/Storage/CreateBucket.cs
  storage/api/Storage/CreateRegionalBucket.cs
  storage/api/Storage/Storage.cs
  storage/api/Storage/Storage.csproj
Labels: cla: yes, samples

#1474 chore: Disable renovate dashboard.
  .github/renovate.json
Labels: cla: yes, samples

#1475 Updating README.md for PubSub, Bigtable, IOT, and Spanner
  appengine/flexible/Pubsub/README.md
  applications/googlehome-meets-dotnetcontainers/Readme.md
  bigtable/api/README.md
  iot/api/README.md
  spanner/api/README.md
Labels: cla: yes, samples
