Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2021-01, with the labels that each got.

#1237 docs: cleanup tagging
  iam/api/Access/AddMember.cs
  spanner/api/Spanner/GetBackupOperations.cs
  spanner/api/Spanner/GetBackups.cs
  spanner/api/Spanner/GetDatabaseOperations.cs
  spanner/api/Spanner/RestoreDatabase.cs
Labels: cla: yes, samples

#1231 feat: adds a new multi region sample
  speech/api/QuickStart/QuickStart.cs
  speech/api/Recognize/Recognize.cs
  speech/api/SpeechTest/SpeechTest.cs
Labels: cla: yes, samples

#1240 feat(IAP): Changes the IAP sample to use Application Default Credentials.
  identity-aware-proxy/IAPClient/IAPClient.cs
  identity-aware-proxy/IAPClientTest/IAPClientTests.cs
  identity-aware-proxy/IAPClientTest/IAPFixture.cs
  identity-aware-proxy/IAPClientTest/IAPTokenVerificationTests.cs
Labels: api: iap, cla: yes, samples

#1243 Add iot team as owners for samples
  CODEOWNERS
Labels: cla: yes, samples

#1225 C# samples for service directory service
  servicedirectory/api/ServiceDirectory.Samples.Tests/CreateEndpointTests.cs
  servicedirectory/api/ServiceDirectory.Samples.Tests/CreateNamespaceTests.cs
  servicedirectory/api/ServiceDirectory.Samples.Tests/CreateServiceTests.cs
  servicedirectory/api/ServiceDirectory.Samples.Tests/DeleteEndpointTests.cs
  servicedirectory/api/ServiceDirectory.Samples.Tests/DeleteNamespaceTests.cs
  servicedirectory/api/ServiceDirectory.Samples.Tests/DeleteServiceTests.cs
  servicedirectory/api/ServiceDirectory.Samples.Tests/ResolveServiceTests.cs
  servicedirectory/api/ServiceDirectory.Samples.Tests/ServiceDirectory.Samples.Tests.csproj
  servicedirectory/api/ServiceDirectory.Samples.Tests/ServiceDirectoryFixture.cs
  servicedirectory/api/ServiceDirectory.Samples/CreateEndpoint.cs
  servicedirectory/api/ServiceDirectory.Samples/CreateNamespace.cs
  servicedirectory/api/ServiceDirectory.Samples/CreateService.cs
  servicedirectory/api/ServiceDirectory.Samples/DeleteEndpoint.cs
  servicedirectory/api/ServiceDirectory.Samples/DeleteNamespace.cs
  servicedirectory/api/ServiceDirectory.Samples/DeleteService.cs
  servicedirectory/api/ServiceDirectory.Samples/ResolveService.cs
  servicedirectory/api/ServiceDirectory.Samples/ServiceDirectory.Samples.csproj
  servicedirectory/api/ServiceDirectory.sln
  servicedirectory/api/runTests.ps1
Labels: cla: yes, samples

#1248 fix(storage): update CustomTime and NonCurrentTime
  storage/api/Storage.Samples/EnableBucketLifecycleManagement.cs
  storage/api/Storage.Samples/Storage.Samples.csproj
Labels: api: storage, cla: yes, samples

#1245 chore(GAE flex): rm unused sendgrid samples
  appengine/flexible/AppEngineFlex.sln
  appengine/flexible/SendGrid/Controllers/HomeController.cs
  appengine/flexible/SendGrid/Program.cs
  appengine/flexible/SendGrid/Properties/launchSettings.json
  appengine/flexible/SendGrid/README.md
  appengine/flexible/SendGrid/SendGrid.csproj
  appengine/flexible/SendGrid/SendgridOptions.cs
  appengine/flexible/SendGrid/Startup.cs
  appengine/flexible/SendGrid/ViewModels/HomeIndex.cs
  appengine/flexible/SendGrid/ViewModels/SendForm.cs
  appengine/flexible/SendGrid/Views/Home/Index.cshtml
  appengine/flexible/SendGrid/Views/Shared/Error.cshtml
  appengine/flexible/SendGrid/Views/Shared/_Layout.cshtml
  appengine/flexible/SendGrid/Views/_ViewImports.cshtml
  appengine/flexible/SendGrid/Views/_ViewStart.cshtml
  appengine/flexible/SendGrid/app.yaml
  appengine/flexible/SendGrid/appsettings.json
  appengine/flexible/SendGrid/deployTests.ps1
  appengine/flexible/SendGrid/runTests.ps1
  appengine/flexible/SendGrid/test.js
Labels: cla: yes, samples

#1246 chore(GAE flex): rm unused sql samples
  appengine/flexible/AppEngineFlex.sln
  appengine/flexible/CloudSql/.gitignore
  appengine/flexible/CloudSql/CloudSql.csproj
  appengine/flexible/CloudSql/Controllers/HomeController.cs
  appengine/flexible/CloudSql/Filters/DbExceptionFilter.cs
  appengine/flexible/CloudSql/Program.cs
  appengine/flexible/CloudSql/Properties/launchSettings.json
  appengine/flexible/CloudSql/README.md
  appengine/flexible/CloudSql/Startup.cs
  appengine/flexible/CloudSql/ViewModels/HomeModel.cs
  appengine/flexible/CloudSql/Views/Home/Index.cshtml
  appengine/flexible/CloudSql/Views/Shared/DbException.cshtml
  appengine/flexible/CloudSql/Views/Shared/Error.cshtml
  appengine/flexible/CloudSql/Views/Shared/_Layout.cshtml
  appengine/flexible/CloudSql/Views/_ViewImports.cshtml
  appengine/flexible/CloudSql/Views/_ViewStart.cshtml
  appengine/flexible/CloudSql/app.yaml
  appengine/flexible/CloudSql/appsettings.json
  appengine/flexible/CloudSql/deployTests.ps1
  appengine/flexible/CloudSql/runTestsWithMySql.ps1
  appengine/flexible/CloudSql/runTestsWithPostgreSql.ps1
  appengine/flexible/CloudSql/test.js
Labels: cla: yes, samples
