Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2024-07, with the labels that each got.

#2705 feat(storagecontrol): Folders samples
  storage/api/Storage.Samples.Tests/StorageControlCreateFolderTest.cs
  storage/api/Storage.Samples.Tests/StorageControlDeleteFolderTest.cs
  storage/api/Storage.Samples.Tests/StorageControlGetFolderTest.cs
  storage/api/Storage.Samples.Tests/StorageControlListFoldersTest.cs
  storage/api/Storage.Samples.Tests/StorageControlRenameFolderTest.cs
  storage/api/Storage.Samples.Tests/StorageFixture.cs
  storage/api/Storage.Samples/StorageControlCreateFolder.cs
  storage/api/Storage.Samples/StorageControlDeleteFolder.cs
  storage/api/Storage.Samples/StorageControlGetFolder.cs
  storage/api/Storage.Samples/StorageControlListFolders.cs
  storage/api/Storage.Samples/StorageControlRenameFolder.cs
Labels: samples

#2713 chore: codecleanup of unused AI Samples
  aiplatform/api/AIPlatform.Samples.Tests/ControllerGenerationTest.cs
  aiplatform/api/AIPlatform.Samples/ControlledGeneration.cs
Labels: samples

#2716 chore: Log for diagnosing Windows CI issues.
  .kokoro/main.ps1
Labels: samples

#2718 chore: More logging for diagnosing Windows CI issues
  .kokoro/main.ps1
Labels: samples

#2720 ci: Run all tests by default
  .kokoro/main.ps1
Labels: samples

#2721 ci: Remove the temporary variable for all directory names.
  .kokoro/main.ps1
Labels: samples

#2723 ci: Remove the empty folders from the list of test folders
  .kokoro/main.ps1
Labels: samples

#2724 ci: Fix typo
  .kokoro/main.ps1
Labels: samples

#2722 ci: Add AIPlatform projects to the existing solution
  aiplatform/api/AIPlatform.Samples.Tests/AIPlatform.Samples.Tests.csproj
  aiplatform/api/AIPlatform.Samples/AIPlatform.Samples.csproj
  aiplatform/api/AIPlatform.sln
Labels: samples

#2725 ci: Remove empty folder names that we get on some environments.
  .kokoro/main.ps1
Labels: samples

#2726 chore: Stop automatic upgrade of some samples to .NET 8
  .github/renovate.json
Labels: samples

#2727 fix(Compute): Fix flake because of firewall not being ready.
  compute/api/Compute.Samples.Tests/ComputeFixture.cs
  compute/api/Compute.Samples.Tests/CreateFirewallRuleAsyncTest.cs
  compute/api/Compute.Samples.Tests/DeleteFirewallRuleAsyncTest.cs
  compute/api/Compute.Samples.Tests/PatchFirewallRuleAsyncTest.cs
Labels: api: compute, samples

#2731 Look for another more probable string in the output
  aiplatform/api/AIPlatform.Samples.Tests/MultimodalAllInputTest.cs
Labels: samples

#2732 build[Functions]: Make ResponseStreaming test target .NET 6
  functions/responsestreaming/StreamBigQuery.Tests/StreamBigQuery.Tests.csproj
Labels: samples

#2741 docs(generativeai): add region tags for code samples
  aiplatform/api/AIPlatform.Samples/GeminiQuickstart.cs
  aiplatform/api/AIPlatform.Samples/PredictChatPromptSample.cs
  aiplatform/api/AIPlatform.Samples/PredictTextPrompt.cs
Labels: samples

#2745 feat(Video Stitcher): add list iterators to list samples
  media/stitcher/api/Stitcher.Samples/ListCdnKeys.cs
  media/stitcher/api/Stitcher.Samples/ListLiveAdTagDetails.cs
  media/stitcher/api/Stitcher.Samples/ListLiveConfigs.cs
  media/stitcher/api/Stitcher.Samples/ListSlates.cs
Labels: samples, api: videostitcher

#2744 chore: cleanup unused region tags
  aiplatform/api/AIPlatform.Samples/GeminiQuickstart.cs
  aiplatform/api/AIPlatform.Samples/MultiTurnChatSample.cs
  aiplatform/api/AIPlatform.Samples/MultimodalMultiImage.cs
  aiplatform/api/AIPlatform.Samples/MultimodalVideoInput.cs
  aiplatform/api/AIPlatform.Samples/WithSafetySettings.cs
Labels: samples
