Repository GoogleCloudPlatform/dotnet-docs-samples, pull requests merged in 2024-12, with the labels that each got.

#2860 chore(acl): delete sample storage_print_bucket_acl_for_user
  storage/api/Storage.Samples.Tests/PrintBucketAclForUserTest.cs
  storage/api/Storage.Samples/PrintBucketAclForUser.cs
Labels: samples

#2856 Add secrets team to codeowners
  .github/blunderbuss.yml
  CODEOWNERS
Labels: samples

#2866 chore(storage): delete sample storage_print_bucket_acl
  storage/api/Storage.Samples.Tests/PrintBucketAclTest.cs
  storage/api/Storage.Samples/PrintBucketAcl.cs
Labels: api: storage, samples

#2865 chore(media): Update codeowners
  .github/blunderbuss.yml
  CODEOWNERS
Labels: samples, api: mediatranslation

#2876 docs(iam): Update QuickStart.cs comments
  iam/api/QuickStart/QuickStart.cs
Labels: samples
